#!/bin/bash
# $Id: addkeywords,v 1.6 2019/05/14 08:17:02 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
# $Revision: 1.6 $
# Author C W Fulford.
# Copyright 2019 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: addkeywords,v 1.6 2019/05/14 08:17:02 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-l) last=$2;shift 2;;
		-s) first=$2;shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.6 $ $Date: 2019/05/14 08:17:02 $"|awk '{print $1,$3,$6}';exit;;  
		*) keywords="$keywords $1";shift;;
	esac
done
config=${config:-/usr/local/etc/${cmd}.cf
echo here ;exit
[ -r $config ]||{echo $cmd: Can't find $config;exit 1}
eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`

##############################
carryon () {
	read -p "Continue [y/n]? " yesno
	[ $yesno != y ] && exit
}

getFiles () {
	dir=`basename \`pwd\`` 
	case $dir in
		raw) ext=CR2;;
		jpg) ext=jpg;;
		*) echo "Extension for $dir unknown" >&2
		   exit;;
	esac
	clear
	echo 
	PS3="Select first: "
	select first in *.$ext ;do
		clear
		echo -e "First file = $first\n"
		break
	done
	PS3="Select last: "
	select last in *$ext ;do
		clear
		break
	done
	files=`ls *.$ext | awk '/'$first'/,/'$last'/{printf("%s ",$1)}'`
	totfiles=`ls *.$ext |wc -w`
}

setKeyword () {
	keyword="$@"
	unset tfiles gfiles
	for f in $files;do
		if ! exiftool -IPTC:keywords $f|grep -q "$keyword"  ;then
			tfiles="$tfiles $f"
		else
			gfiles="$gfiles $f"
		fi
	done

	if [ -n "$gfiles" ];then
		totdone=`echo $gfiles|wc -w`
		echo -e "\n\"$keyword\" already exists in $totdone files:"
	fi
	
	if [ -z "$tfiles" ];then
		echo "Nothing to be done with $keyword" 
	else
		echo -e "\nAdding keyword \"$keyword\" to ${#tfiles} files\n" 
		echo " $tfiles"|pg
	fi
	read -p "Continue[y/n/q]? " yesno </dev/tty
	case  $yesno in
		n) getFiles ;;
		y) exiftool -IPTC:keywords+="$keyword" $tfiles
			rm *original
			;;
		*) exit;;
	esac
}

if [ ${#keywords} -lt 1 ];then
	clear
	echo 
	read -p "Enter comma separated list of keywords: " keywords
fi

################# Main Procedure #####################

echo $keywords|awk -F, '{for(i=1; i<=NF; i++) print($i)}'|
while read keyword;do
	grep -q ^$keyword$ /usr/local/etc/keywords ||{
		echo "Keyword \"$keyword\" is not available" >&2
		read -p "Edit keywords now [y/n]? " yesno </dev/tty 
		if [ $yesno = "y" ];then 
			sudo vi /usr/local/etc/keywords
		fi
	}
done

echo here
getFiles


echo $keywords	
echo $keywords|awk -F, '{for(i=1; i<=NF; i++) print($i)}'|
while read keyword;do
	setKeyword "$keyword"
done	 

