#!/bin/bash
# $Id: addkeywords,v 1.87 2019/06/23 21:45:56 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/addkeywords,v $
# $Revision: 1.87 $
# Author C W Fulford.
# Copyright 2019 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: addkeywords,v 1.87 2019/06/23 21:45:56 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0; trap read debug;shift;;
		-h) hostid=$2;shift 2;;			
		-l) last=$2;shift 2;;
		-s) first=$2;shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.87 $ $Date: 2019/06/23 21:45:56 $"|awk '{print $1,$3,$6}';exit;;  
		*) keywords="$keywords $1";shift;;
	esac
done
dict=/usr/local/etc/keywords

##############################
carryon () {
	read -p "Continue [y/n]? " yesno
	[ $yesno != y ] && exit
}

getFiles () {
	dir=`basename \`pwd\`` 
	case $dir in
		raw) ext=CR2;;
		jpg) ext=jpg;;
		tif) ext=tif;;
		*) echo "Extension for $dir unknown" >&2
		   exit;;
	esac
	clear
	echo 
	PS3="Select first: "
	select first in *.$ext ;do
		clear
		echo -e "First file = $first\n"
		break
	done
	PS3="Select last: "
	select last in *$ext ;do
		clear
		break
	done
	farray=(`ls *.$ext | awk '/'$first'/,/'$last'/{printf "%s ",$0}'`)
}

chkFiles () {
	keyword="$@"
	for ((i=0; i<${#farray[@]}; i++));do
		echo ${farray[$i]}
		if ! exiftool -IPTC:keywords ${farray[$i]}|
		  grep -q "$keyword";then
			tfiles+=(${farray[$i]})
		else
			gfiles+=(${farray[$i]})
			echo ${farray[$i]}
		fi
			echo tfiles ${tfiles[$i]}
			echo gfiles ${gfiles[$i]}
	done
	if [ ${#gfiles[@]} -gt 0 ];then
		echo -e "\n\"$keyword\" already exists in ${#gfiles[@]} files:"
	fi
	if [ ${#tfiles[@]} -gt 0 ];then
		echo -e "\n\"$keyword\" required in ${#tfiles[@]} files"
		#echo $tfiles|pr -t -8 -
		read -p "Add keyword[y/n/q]? " reply </dev/tty
		case $reply  in
			y) return ${#tfiles[@]};;
			n) return 0;;
			q) return -1;;
		esac
	else
		echo -e "Nothing to be done for \"$keyword\"">&2
		return 0
	fi
}
chkKeyword () { 
	keyword="$@"
	if  grep -q ^$keyword$ $dict ;then
		return 0
	else
		# Try partial match
		IFS=: matches=(`awk '/'$keyword'/{printf "%s:",$0}' $dict`)

		# If nothing found offer to edit dictionary 
		if [ ${#matches[@]} -lt 1 ];then
			echo "Keyword \"$keyword\" is not available" >&2
			read -p "Edit keywords now [y/n]? " yesno </dev/tty 
			if [ $yesno = "y" ];then 
				sudo vi $dict </dev/tty
			fi
		else
			for ((i=0; i<${#matches[@]}; i++));do
				echo "${i} ${matches[$i]}"
			done
			read -p "Select words or quit [#/q]: " s </dev/tty
			keyword="${matches[$s]}"
		fi
	fi
}

setKeyword () {
	keyword="$@"
	echo ${#tfiles[@]}
	for ((i=0; i<${#tfiles[@]}; i++));do
		echo target ${tfiles[$i]}
		exiftool -IPTC:keywords+="$keyword" ${tfiles[$i]}
	echo here
	done
	rm *original
}

################# Main Procedure #####################
getFiles
if [ ${#keywords} -lt 1 ];then
	clear
	echo 
	read -p "Enter comma separated list of keywords: " keywords
fi
echo $keywords|awk -F, '{for(i=1; i<=NF; i++) print($i)}'|
while read keyword;do
echo $keyword
	chkKeyword "$keyword"
	gfiles=()
	tfiles=()
	chkFiles "$keyword" 
	todo=$?
	echo todo $todo
	echo n ${#tfiles[@]}
	if [ $todo -gt 0 ];then
		setKeyword "$keyword"
	fi
done	
echo "Keyword updates completed" 

